# -----------------------------------------------------------------------------
# Configuration for the Document Processing Pipeline
# -----------------------------------------------------------------------------

# --- Paths and Directories ---
paths:
  # Path to the local embedding model directory, as specified in the spec.
  embedding_model_dir: "models/qwen3-embed-0.6b"
  #Path to the docling models
  artifacts_path : "models"
  # Name of the temporary folder for intermediate processing files.
  temp_dir_name: "_temp"
  # Name of the folder to store documents that failed processing permanently.
  failed_dir_name: "_failed"
  # Path for the file-based Qdrant database.
  qdrant_db_path: "local_qdrant_db"
  # Log file name.
  log_file: "pipeline.log"

# --- LLM and Tokenizer Configuration ---
llm:
  # The base URL for the local Ollama server.
  ollama_base_url: "http://127.0.0.1:9292"
  # Specific model assignments for different tasks to ensure the correct model is used.
  tokenizer_model: "unsloth/Mistral-Small-3.2-24B-Instruct-2506"
  # Global token limit for any input sent to an LLM.
  max_input_tokens: 10000

# --- Vector Database Configuration (Qdrant) ---
qdrant:
  collection_name: "engineering_document_embeddings"
  vector_size: 1024
  distance_metric: "Cosine" # As specified: Cosine similarity.

# --- Processing Parameters ---
processing_params:
  # Maximum number of processing attempts before a document is marked as failed.
  max_retries: 2
  # Word document specific parameters.
  word:
    # Token count threshold to distinguish between 'small' and 'large' documents.
    small_doc_threshold_tokens: 5000
    # Model assignments for Word processing
    title_model : "granite_q4"
    structure_model : "mistral-s"
    summary_model : "granite-8b-q6"
  # Excel document specific parameters.
  excel:
    # For large tables, only the first N rows are sent to the LLM for analysis.
    table_truncation_rows: 100

# --- External Services Configuration ---
services:
  # Configuration for the unoserver instance used for DOC -> PDF conversion.
  unoserver:
    host: "localhost"
    port: 2002